In [3]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [4]:
df=pd.read_pickle("G:\\My Drive\\Projects\\110_JetscapeMl\\hm.jetscapeml.data\\simulation_results\\jet_ml_benchmark_config_01_to_09_alpha_0.2_0.3_0.4_q0_1.5_2.0_2.5_MMAT_MLBT_size_1000_shuffled.pkl")

type(df)
dataset_x=df[0]
dataset_y=df[1]
dataset_x.shape

(1000, 32, 32)

In [5]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(dataset_x,dataset_y, test_size=0.2,random_state=25)

In [6]:
x_train.shape,len(x_train)

((800, 32, 32), 800)

In [7]:
x_max=max(x_train.max(),x_test.max())
x_max

86.90838000000002

In [8]:
x_train_flatten=x_train.reshape(len(x_train),32*32)
x_test_flatten=x_test.reshape(len(x_test),32*32)
x_train_scaled=x_train_flatten.copy()
x_test_scaled=x_test_flatten.copy()
x_train_scaled=x_train_scaled/x_max
x_test_scaled=x_test_scaled/x_max

In [9]:
from sklearn.preprocessing import OneHotEncoder


y_train_0_categorical = np.array(y_train[:,0]).reshape(-1, 1)
y_test_0_categorical = np.array(y_test[:,0]).reshape(-1, 1)

encoder = OneHotEncoder(sparse_output=False)
y_train_0_categorical_encoded = encoder.fit_transform(y_train_0_categorical)
y_test_0_categorical_encoded = encoder.transform(y_test_0_categorical)
y_test_0_categorical_encoded

array([[1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.

In [10]:
model=keras.Sequential([
    keras.layers.Dense(2,input_shape=(32*32,),activation='sigmoid',kernel_initializer='ones',bias_initializer='zeros')
])
model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics='accuracy')
model.fit(x_train_scaled,y_train_0_categorical_encoded,epochs=500)



Epoch 1/500


25/25 [==============================] - 1s 2ms/step - loss: 0.8264 - accuracy: 0.5238
Epoch 2/500
25/25 [==============================] - 0s 2ms/step - loss: 0.8178 - accuracy: 0.6988
Epoch 3/500
25/25 [==============================] - 0s 2ms/step - loss: 0.8097 - accuracy: 0.7138
Epoch 4/500
25/25 [==============================] - 0s 2ms/step - loss: 0.8019 - accuracy: 0.7038
Epoch 5/500
25/25 [==============================] - 0s 2ms/step - loss: 0.7944 - accuracy: 0.7038
Epoch 6/500
25/25 [==============================] - 0s 2ms/step - loss: 0.7873 - accuracy: 0.7100
Epoch 7/500
25/25 [==============================] - 0s 2ms/step - loss: 0.7805 - accuracy: 0.7063
Epoch 8/500
25/25 [==============================] - 0s 2ms/step - loss: 0.7740 - accuracy: 0.7088
Epoch 9/500
25/25 [==============================] - 0s 2ms/step - loss: 0.7678 - accuracy: 0.7163
Epoch 10/500
25/25 [==============================] - 0s 1ms/step - loss: 0.7619 - accuracy: 0.7113
Epoch

In [11]:
model.evaluate(x_test_scaled,y_test_0_categorical_encoded)

7/7 [==============================] - 0s 2ms/step - loss: 0.7349 - accuracy: 0.5750


[0.7349014282226562, 0.574999988079071]

In [12]:
model.predict(x_test_scaled)

7/7 [==============================] - 0s 2ms/step


array([[0.5667193 , 0.51355696],
       [0.21448503, 0.81332994],
       [0.666027  , 0.3054104 ],
       [0.6284591 , 0.3808656 ],
       [0.40645054, 0.54745764],
       [0.21677996, 0.7539305 ],
       [0.52186227, 0.38843414],
       [0.49180418, 0.4621419 ],
       [0.07965852, 0.931682  ],
       [0.19964884, 0.8253988 ],
       [0.63112223, 0.4008102 ],
       [0.21774232, 0.7752779 ],
       [0.4571619 , 0.48457792],
       [0.3976989 , 0.60729927],
       [0.25254276, 0.7592449 ],
       [0.67567366, 0.31243575],
       [0.3770208 , 0.6276852 ],
       [0.9729656 , 0.03296144],
       [0.41747844, 0.61167175],
       [0.61361307, 0.38025752],
       [0.55026513, 0.46220952],
       [0.68694717, 0.373772  ],
       [0.40724942, 0.5661276 ],
       [0.8687728 , 0.15795253],
       [0.43015555, 0.40727952],
       [0.51187724, 0.52054983],
       [0.26789835, 0.744986  ],
       [0.6387392 , 0.3518471 ],
       [0.6704412 , 0.27838787],
       [0.3269531 , 0.6793057 ],
       [0.

In [13]:
y_test_0_categorical_encoded

array([[1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.

In [14]:
coef,intercept=model.get_weights()
coef,intercept

(array([[ 0.5514209 ,  0.46758682],
        [ 6.2244506 , -4.0444717 ],
        [-1.1691525 ,  3.1596472 ],
        ...,
        [ 2.739781  , -1.2082952 ],
        [ 1.6937006 , -0.20735595],
        [ 2.2846842 , -0.95905846]], dtype=float32),
 array([-0.22536701, -1.5207086 ], dtype=float32))

In [15]:
def sigmoid(x):
    import math
    return 1/(1+math.exp(-x))
sigmoid(26)

0.999999999994891

In [16]:
coef[:,0].shape,intercept[0].shape, x_test_scaled[0].shape

((1024,), (), (1024,))

In [17]:
def prediction_function(flattern_event_image):
    # weighted_sum=coef[0,0]*pixel1+coef[1,0]*pixel2+intercept
    # weighted_sum= np.dot(coef[:,0],flattern_event_image)+intercept[0]
    weighted_sum=np.dot(coef[:,0],flattern_event_image)+intercept[0]
    return sigmoid(weighted_sum)
# print(coef[0,0])
# print(coef[0,1])
# print(x_test_scaled[0,0])
# print(x_test_scaled[0,1])
# print(coef.shape)
# print(coef[:,0].shape)
# print(x_test_scaled.shape)
# print(x_test_scaled[0,:].shape)
# print(np.dot(coef[:,0],x_test_scaled[0,:])+intercept[0])
x_test_1_mmat_prediction=prediction_function(x_test_scaled[0,:])
print(x_test_1_mmat_prediction)
# prediction_function(x_test_scaled[0,0],x_test_scaled[0,1])

0.5667193006385417


In [18]:
def log_loss(y_true,y_predicted):
    epsilon=1e-15
    y_predicted_new=[max(i,epsilon) for i in y_predicted]
    y_predicted_new=[min(i,1-epsilon) for i in y_predicted_new]
    y_predicted_new=np.array(y_predicted_new)
    return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

In [19]:
def sigmoid_numpy(X):
    return 1/(1+np.exp(-X))
sigmoid_numpy(np.array([12,0,1]))

array([0.99999386, 0.5       , 0.73105858])

In [24]:
class myNN:
    def __init__(self):
        self.w=np.ones(1024)
        self.bias=0
        pass
    def fit(self,X,y,epoch,loss_threshold):
        self.w,self.bias=self.gradient_descent(X,y,epoch,loss_threshold)
    def predict(self,X_test):
        weighted_sum=np.dot(X_test,self.w)+self.bias
        return sigmoid_numpy(weighted_sum)

    def gradient_descent(self,event_image_flatten_items,y_true,epoch,loss_threshold):
        #wi ,bias
        w=np.ones(1024)
        bias=0
        rate=0.5
        n=len(event_image_flatten_items)
        for i in range (epoch):
            weighted_sum=np.dot(w,event_image_flatten_items.T)+bias
            # print(weighted_sum.shape)
            y_predicted=sigmoid_numpy(weighted_sum)
            # print(y_predicted.shape)
            loss=log_loss(y_true,y_predicted)
            # print(loss,loss.shape)

            # print((y_predicted-y_true).shape)
            # print(np.transpose(event_image_flatten_items).shape)
            w_d=(1/n)*np.dot(np.transpose(event_image_flatten_items),(y_predicted-y_true))
            bias_d=np.mean(y_predicted-y_true)
            w=w-rate*w_d
            bias=bias-rate*bias_d
            if i%50==0:
                print(f'Epoch:{i},w:{w},bias:{bias},loss:{loss}')
            if loss<=loss_threshold:
                print(f'Epoch:{i},w:{w},bias:{bias},loss:{loss}')
                break

        return w,bias
    

In [25]:
customModel=myNN()
customModel.fit(x_train_scaled,y_train_0_categorical_encoded[:,0],1000,0.4965)


Epoch:0,w:[0.99995363 1.00000584 0.9999852  ... 0.99999427 0.99999327 0.99997834],bias:-0.12115613486045103,loss:0.8673273379624098
Epoch:50,w:[0.99926978 1.00070079 0.99958429 ... 1.00009475 0.99997362 1.00030263],bias:-1.0543575815522688,loss:0.7303184206497995
Epoch:100,w:[0.99888961 1.00146445 0.9992465  ... 1.00026689 1.00001398 1.00088291],bias:-1.056704074253488,loss:0.727858900947588
Epoch:150,w:[0.99851649 1.00222465 0.99891044 ... 1.00044071 1.00005685 1.00146409],bias:-1.057558492640881,loss:0.7255270762576788
Epoch:200,w:[0.99814986 1.00298149 0.99857593 ... 1.00061608 1.00010204 1.00204569],bias:-1.0581224272248835,loss:0.7233109809315624
Epoch:250,w:[0.99778955 1.00373513 0.99824291 ... 1.00079295 1.00014939 1.00262758],bias:-1.0584148647076066,loss:0.7212001091202057
Epoch:300,w:[0.99743537 1.00448572 0.99791129 ... 1.00097128 1.0001988  1.00320965],bias:-1.0584527358981706,loss:0.7191850593690716
Epoch:350,w:[0.99708716 1.00523342 0.997581   ... 1.00115102 1.00025013 1.

In [ ]:
coef,intercept

(array([[ 0.5631091 ,  0.48679867],
        [ 6.1786647 , -3.9957356 ],
        [-1.173758  ,  3.1655056 ],
        ...,
        [ 2.7341397 , -1.1681086 ],
        [ 1.6804162 , -0.19900237],
        [ 2.2389245 , -0.93854165]], dtype=float32),
 array([-0.2209721, -1.5213886], dtype=float32))

In [ ]:
prediction=customModel.predict(x_test_scaled)
print(prediction[:10])


[0.54757213 0.49257629 0.50773664 0.5339558  0.44736922 0.42647116
 0.45361437 0.48976601 0.39375018 0.45002782]


In [ ]:
tensor_prediction=model.predict(x_test_scaled)
print(tensor_prediction[:10])

7/7 [==============================] - 0s 2ms/step
[[0.56728196 0.512267  ]
 [0.21465604 0.81357497]
 [0.6657622  0.30535066]
 [0.62919235 0.380597  ]
 [0.406397   0.5478472 ]
 [0.21935749 0.751834  ]
 [0.52231216 0.3882455 ]
 [0.4921597  0.462019  ]
 [0.07845338 0.9320981 ]
 [0.1986526  0.82719576]]
