In [2]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [43]:
df=pd.read_pickle("G:\\My Drive\\Projects\\110_JetscapeMl\\hm.jetscapeml.data\\simulation_results\\jet_ml_benchmark_config_01_to_09_alpha_0.2_0.3_0.4_q0_1.5_2.0_2.5_MMAT_MLBT_size_1000_shuffled.pkl")

type(df)
dataset_x=df[0]
dataset_y=df[1]
dataset_x.shape

(1000, 32, 32)

In [44]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(dataset_x,dataset_y, test_size=0.2,random_state=25)

In [45]:
x_train.shape,len(x_train)

((800, 32, 32), 800)

In [46]:
x_max=max(x_train.max(),x_test.max())
x_max

86.90838000000002

In [48]:
x_train_flatten=x_train.reshape(len(x_train),32*32)
x_test_flatten=x_test.reshape(len(x_test),32*32)
x_train_scaled=x_train_flatten.copy()
x_test_scaled=x_test_flatten.copy()
x_train_scaled=x_train_scaled/x_max
x_test_scaled=x_test_scaled/x_max

In [50]:
from sklearn.preprocessing import OneHotEncoder


y_train_0_categorical = np.array(y_train[:,0]).reshape(-1, 1)
y_test_0_categorical = np.array(y_test[:,0]).reshape(-1, 1)

encoder = OneHotEncoder(sparse_output=False)
y_train_0_categorical_encoded = encoder.fit_transform(y_train_0_categorical)
y_test_0_categorical_encoded = encoder.transform(y_test_0_categorical)
y_test_0_categorical_encoded

array([[1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.

In [52]:
model=keras.Sequential([
    keras.layers.Dense(2,input_shape=(32*32,),activation='sigmoid',kernel_initializer='ones',bias_initializer='zeros')
])
model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics='accuracy')
model.fit(x_train_scaled,y_train_0_categorical_encoded,epochs=5000)

Epoch 1/5000
25/25 [==============================] - 1s 2ms/step - loss: 0.8264 - accuracy: 0.5362
Epoch 2/5000
25/25 [==============================] - 0s 2ms/step - loss: 0.8180 - accuracy: 0.6700
Epoch 3/5000
25/25 [==============================] - 0s 2ms/step - loss: 0.8099 - accuracy: 0.7013
Epoch 4/5000
25/25 [==============================] - 0s 2ms/step - loss: 0.8021 - accuracy: 0.6988
Epoch 5/5000
25/25 [==============================] - 0s 2ms/step - loss: 0.7946 - accuracy: 0.7075
Epoch 6/5000
25/25 [==============================] - 0s 2ms/step - loss: 0.7876 - accuracy: 0.7075
Epoch 7/5000
25/25 [==============================] - 0s 2ms/step - loss: 0.7808 - accuracy: 0.7075
Epoch 8/5000
25/25 [==============================] - 0s 3ms/step - loss: 0.7743 - accuracy: 0.7013
Epoch 9/5000
25/25 [==============================] - 0s 3ms/step - loss: 0.7682 - accuracy: 0.7088
Epoch 10/5000
25/25 [==============================] - 0s 2ms/step - loss: 0.7623 - accuracy: 0.7150

In [53]:
model.evaluate(x_test_scaled,y_test_0_categorical_encoded)

7/7 [==============================] - 0s 2ms/step - loss: 1.2706 - accuracy: 0.6450


[1.2705960273742676, 0.6449999809265137]

In [54]:
model.predict(x_test_scaled)

7/7 [==============================] - 0s 2ms/step


array([[6.55543864e-01, 4.06889141e-01],
       [1.57427113e-03, 9.98750269e-01],
       [9.35388029e-01, 5.93925714e-02],
       [4.86984581e-01, 5.25244713e-01],
       [8.03170264e-01, 1.86246708e-01],
       [4.90243062e-02, 9.43635285e-01],
       [8.52173567e-01, 1.15044110e-01],
       [3.41861904e-01, 6.18629277e-01],
       [5.31363767e-04, 9.99497771e-01],
       [2.95421014e-05, 9.99983549e-01],
       [4.60336268e-01, 5.66169262e-01],
       [3.49082977e-01, 6.43756092e-01],
       [6.26077175e-01, 3.38556409e-01],
       [2.97276050e-01, 7.27527082e-01],
       [5.64725278e-03, 9.94326591e-01],
       [9.64566648e-01, 3.97092924e-02],
       [2.11906552e-01, 8.99199963e-01],
       [1.00000000e+00, 5.86887816e-10],
       [5.19573927e-01, 5.25086045e-01],
       [8.73261094e-01, 1.40025318e-01],
       [9.09685731e-01, 9.94626954e-02],
       [7.72631168e-01, 2.66495496e-01],
       [4.12820011e-01, 5.71856618e-01],
       [9.99954462e-01, 1.05959814e-04],
       [8.892495

In [56]:
y_test_0_categorical_encoded

array([[1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.

In [58]:
coef,intercept=model.get_weights()
coef,intercept

(array([[ 12.695803  , -11.909882  ],
        [ 41.63649   , -37.646797  ],
        [-15.823772  ,  18.508417  ],
        ...,
        [ 11.355332  ,  -9.220174  ],
        [  1.2164333 ,  -0.37881213],
        [  0.5676731 ,   0.16453199]], dtype=float32),
 array([ 6.2737193, -7.6548557], dtype=float32))

In [60]:
def sigmoid(x):
    import math
    return 1/(1+math.exp(-x))
sigmoid(26)

0.999999999994891

In [72]:
coef[:,0].shape,intercept[0].shape, x_test_scaled[0].shape

((1024,), (), (1024,))

In [74]:
def prediction_function(flattern_event_image):
    weighted_sum= np.dot(coef[:,0],flattern_event_image)+intercept[0]
    return sigmoid(weighted_sum)
prediction_function(x_test_scaled[0])

0.6555437526744033

In [75]:
def log_loss(y_true,y_predicted):
    epsilon=1e-15
    y_predicted_new=[max(i,epsilon) for i in y_predicted]
    y_predicted_new=[min(i,1-epsilon) for i in y_predicted_new]
    y_predicted_new=np.array(y_predicted_new)
    return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

In [76]:
def sigmoid_numpy(X):
    return 1/(1+np.exp(-X))
sigmoid_numpy(np.array([12,0,1]))

array([0.99999386, 0.5       , 0.73105858])

In [185]:
def gradient_descent(event_image_flatten,y_true,epoch,threshold):
    #wi ,bias
    w=np.ones(len(event_image_flatten[0]))
    # bias=np.zeros(len(event_image_flatten[0]))
    bias=0
    rate=0.5
    n=len(event_image_flatten)
    for i in range (epoch):
        # print(event_image_flatten.shape)
        weighted_sum=np.array([])
        for event_image_flatten_item in  event_image_flatten:
            current_weighted_sum=np.dot(event_image_flatten_item,w)+bias
            # print(current_weighted_sum)
            # break
            weighted_sum=np.append(weighted_sum,np.array([current_weighted_sum]))
            # print(current_weighted_sum)
            # print(current_weighted_sum.shape)
            # break
        # weighted_sum=np.dot(event_image_flatten,w)+bias
        # print(weighted_sum)
        # print(weighted_sum.shape)
        # break
        y_predicted=sigmoid_numpy(weighted_sum)
        
        # print(y_predicted.shape)
        # print(y_true.shape)
        # break
        loss=log_loss(y_true,y_predicted)
        # print(loss)
        # print(event_image_flatten.shape)
        # difference=y_predicted-y_true
        # print(difference.shape)
        
        w_d=(1/n)*np.dot(np.transpose(event_image_flatten),(y_predicted-y_true))
        # print(w_d.shape)
        b_d=np.mean(y_predicted-y_true)
        w=w-rate*w_d
        bias=bias-rate*b_d
        print(f'Epoch:{i},w:{w},bias:{bias},loss:{loss}')
        if loss<=threshold:
            break

    return w,bias

In [186]:
gradient_descent(x_train_scaled,y_train_0_categorical_encoded[:,0],1000,0.1607)

Epoch:0,w:[0.99996377 1.00000456 0.99998844 ... 0.99999552 0.99999474 0.99998308],bias:-0.12115613486045103,loss:0.8673273379624098
Epoch:1,w:[0.99993051 1.00000987 0.99997749 ... 0.99999174 0.99999005 0.99996872],bias:-0.2303837668622461,loss:0.839201044583061
Epoch:2,w:[0.99990005 1.00001589 0.99996713 ... 0.99998864 0.99998591 0.99995678],bias:-0.3282972022361316,loss:0.8163968688675043
Epoch:3,w:[0.99987222 1.00002257 0.99995732 ... 0.99998615 0.99998227 0.99994712],bias:-0.41564435693756896,loss:0.7981080892520009
Epoch:4,w:[0.99984681 1.00002986 0.999948   ... 0.99998425 0.99997911 0.99993955],bias:-0.4932520615326207,loss:0.7835744244606893
Epoch:5,w:[0.99982361 1.00003769 0.99993914 ... 0.99998286 0.99997637 0.99993388],bias:-0.5619792365689456,loss:0.7721115824271371
Epoch:6,w:[0.99980241 1.00004602 0.9999307  ... 0.99998195 0.99997402 0.99992994],bias:-0.6226802786232649,loss:0.763125400726405
Epoch:7,w:[0.999783   1.00005479 0.99992263 ... 0.99998146 0.99997202 0.99992754],b

(array([0.99439265, 1.01158468, 0.99480099, ..., 1.00276811, 1.00077179,
        1.00885718]),
 -1.0500095264601155)

In [119]:
coef[:,0],intercept[0]

(array([ 12.695803 ,  41.63649  , -15.823772 , ...,  11.355332 ,
          1.2164333,   0.5676731], dtype=float32),
 6.2737193)